name: python_yolo_env
channels:
 - pytorch
 - defaults
 - conda-forge
dependencies:
 - python=3.11
 - pip
 - pytorch
 - torchvision
 - pip:
    - numpy
    - pandas
    - matplotlib
    - opencv-python
    - albumentations
    - scipy
    - pyyaml
    - tqdm
    - overrides
    - torchsummary
    - pytorch-lightning
    - tensorboard
    - jupyterlab
    - coverage
    
