name: SE_ENV
channels:
  - pytorch
dependencies:
  - pytorch
  - torchvision
  - pip
  - pip:
    - torchsummary
    - pytorch-lightning
    - jupyterlab
    - numpy
    - pandas
    - matplotlib
    - wandb
    - sklearn
    - opencv-python
    
